### ISSUE TITLE
Where is the code ??

### ISSUE THREAD

**Issue by hakanonymos** [sinanaeemi/BajGir#1]
Hello thabk you for this project but where is the code of this project??

**Comment by sinanaeemi** [comment]
thanks for the interest.
I have not found the time yet to make corrections and upload the code.
Sorry about that

**Comment by hakanonymos** [comment]
ok can you send me the source code from my email adresse ?? i want to learn that or can you upload here ?? or any private link to see that

**Comment by sinanaeemi** [comment]
Sure,
I will send you the code,
your gonna have to figure out how to run it though.
its a little messy.

**Comment by hakanonymos** [comment]
bro send me a link to download or directly with my email : hakanonymos@hotmail.com

**Comment by sinanaeemi** [comment]
Good luck.
it needs debugging and some fixing.
but it runs fine.
it is three separate projects.
you'll figure it out.
